twilio:
  account_sid: AC4efd5427028ba8729fba06f9e31d51f7
  auth_token: bd97b6d1b1d8893460ec94dbd157e186
  service_id: VAd4c4e647bd6992a17a96a62650261ccb

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: ${port:5000}
spring:
  datasource:
    driverClassName: ${JDBC_DATABASE_DRIVER:}
    password: ${JDBC_DATABASE_PASSWORD:}
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT:}
        format_sql: true
        hb2dll:
          auto: update
        id:
          new_generator_mappings: false
        show:
          sql: true

  mail:
    host: smtp.gmail.com
    username: haudt3.fs@gmail.com
    password: Vanngu01
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


